# Generated by Django 4.1.7 on 2023-03-05 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostsApp', '0003_alter_post_post_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
