# Generated by Django 4.1.7 on 2023-03-06 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostsApp', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
